admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin
admin_actu:
    resource: "@AdminBundle/Resources/config/actu_routing.yml"
    prefix:   /admin/actu
admin_parametre:
    resource: "@AdminBundle/Resources/config/parametre_routing.yml"
    prefix:   /admin/parametre
admin_appel:
    resource: "@AdminBundle/Resources/config/appel_routing.yml"
    prefix: /admin/module/appel

admin_sous_item:
    resource: "@AdminBundle/Resources/config/sous_item_routing.yml"
    prefix: /admin/moins26/sous_item

admin_antenne:
    resource: "@AdminBundle/Resources/config/antenne_routing.yml"
    prefix: /admin/module/antenne

admin_offres:
    resource: "@AdminBundle/Resources/config/offre_routing.yml"
    prefix: /admin/module/offre
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

