admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }
admin_categorie:
    path: /categorie
    defaults: { _controller: AdminBundle:Admin:categorie }
admin_modules:
    path: /modules
    defaults: { _controller: AdminBundle:Admin:module }
admin_moins26:
    path:     /moins26
    defaults: { _controller: AdminBundle:Moins26:index }
admin_moins26_update:
    path: /moins26/{id}/update
    defaults: { _controller: AdminBundle:Moins26:update }

