admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Admin:index }
admin_categorie:
    path: /categorie
    defaults: { _controller: AdminBundle:Admin:categorie }
admin_media:
    path: /media
    defaults: { _controller: AdminBundle:Media:home }
admin_modules:
    path: /modules
    defaults: { _controller: AdminBundle:Admin:module }
admin_moins26:
    path:     /moins26
    defaults: { _controller: AdminBundle:Moins26:index }
admin_plus26:
    path:     /plus26
    defaults: { _controller: AdminBundle:Plus26:index }
admin_employeur:
    path:     /employeur
    defaults: { _controller: AdminBundle:Employeur:index }
admin_moins26_update:
    path: /moins26/{id}/update
    defaults: { _controller: AdminBundle:Moins26:update }
    requirements:
                    id: \d+
admin_employeur_update:
    path: /employeur/{id}/update
    defaults: { _controller: AdminBundle:Employeur:update }
    requirements:
                    id: \d+
admin_plus26_update:
    path: /plus26/{id}/update
    defaults: { _controller: AdminBundle:Plus26:update }
    requirements:
                    id: \d+
admin_media_delete:
    path: /media/{image}/delete
    defaults: { _controller: AdminBundle:Media:delete }
admin_media_article:
    path: /media/articles
    defaults: { _controller: AdminBundle:Media:mediaArticle }
admin_media_miniature:
    path: /media/miniature
    defaults: { _controller: AdminBundle:Media:mediaMiniature }
admin_agenda:
    path: /agenda
    defaults: { _controller: AdminBundle:Agenda:index }
admin_encart:
    path: /encart
    defaults: { _controller: AdminBundle:Encart:home }
admin_encart_update:
    path: /encart/{id}/edit
    defaults: { _controller: AdminBundle:Encart:update }
    requirements:
                        id: \d+
admin_qsn:
    path: /qsn
    defaults: { _controller: AdminBundle:QuiSommesNous:index}


