admin_sous_item:
    path: /{id}
    defaults: { _controller: AdminBundle:AdminSousItem:index }
    requirements:
        id: \d+
sous_item_new:
    path: /{id}/new
    defaults: { _controller: AdminBundle:AdminSousItem:new }
    requirements:
        id: \d+

sous_item_update:
    path: /{id}/update
    defaults: { _controller: AdminBundle:AdminSousItem:update }
    requirements:
        id: \d+

sous_item_delete:
    path: /{id}/delete
    defaults: { _controller: AdminBundle:AdminSousItem:delete }
    requirements:
        id: \d+